image: python:3.8

stages:
  - test
  - migrate
  - collectstatic

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  stage: test
  script:
    - python manage.py test
  only:
    - master

migrate:
  stage: migrate
  script:
    - python manage.py migrate
  only:
    - master

collectstatic:
  stage: collectstatic
  script:
    - python manage.py collectstatic --noinput
  only:
    - master

