# Generated by Django 5.0.3 on 2024-04-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeospatialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='geospatial_images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('ndvi_image', models.ImageField(blank=True, null=True, upload_to='processed_images/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
